Feature/api generation
utopia-rise/godot-jvm pull request #57
Opened 2021-01-31 01:21 UTC by piiertho

Draft to check build and generated code is not displayed in review

2021-01-31 13:00 UTC, chippmann commented
To document some debugging and discussions from discod:
With this current impl most likly `496` methods are not working.
Prime example `ResourceLoader::load`

The reason being: they are not in the `ClassDB` which we currently use in `gd_kotlin.cpp` to get the `MethodBind` of engine methods. Hence the methods cannot be found and called during runtime.
All those methoda have in common that they are `virtual` functions.

But we cannot just ditch them as we need them to work. C# is generating it's own `api.json`. Most likely because of this reason.
We need to investicate the C# code to see how they have managed to make functions like `ResourceLoader::load` work.

2021-01-31 14:10 UTC, chippmann commented
Some further investigations on the cSharp code lead to this:
```csharp
        private const string nativeName = "_ResourceLoader";

        [DebuggerBrowsable(DebuggerBrowsableState.Never)]
        private static IntPtr method_bind_1 = Object.godot_icall_Object_ClassDB_get_method(nativeName, "load");

        [GodotMethod("load")]
        public static Resource Load(string path, string typeHint = "", bool noCache = false)
        {
            return NativeCalls.godot_icall_3_1107(method_bind_1, ptr, path, typeHint, noCache);
        }
```

The class name in the ClassDB seems to be `_ResourceLoader` and not `ResourceLoader`.

The following example also supports this:
```gdscript
func _ready():
    print(ClassDB.class_has_method("_ResourceLoader", "load"))
    print(ClassDB.class_has_method("ResourceLoader", "load"))
    print(ClassDB.class_has_method("Node", "get_children"))
```
Prints:
`True`
`False`
`True`

2021-02-05 20:04 UTC, chippmann requested changes

2021-02-05 20:04 UTC, chippmann commented on kt/godot-library/build.gradle.kts
> +    dependsOn(tasks.generateAPI)
Setting the comment here as the api-generator plugin has no PR:
I would put the task `generateApi` into the group `godot-jvm` ike we do in the main gradle plugin

2021-02-08 16:57 UTC, chippmann approved these changes

2021-02-08 17:37 UTC, CedNaru approved these changes

2021-02-09 03:02 UTC, raniejade approved these changes

2021-02-09 07:05 UTC, merged