Support nullables as function params and return types
utopia-rise/godot-jvm pull request #74
Opened 2021-02-22 19:20 UTC by chippmann

We forgot to support nullables as function params and return types. This implements it together with some tests that test this.

2021-02-23 11:02 UTC, CedNaru approved these changes

2021-02-24 08:04 UTC, piiertho requested changes

2021-02-24 08:04 UTC, piiertho commented on kt/godot-runtime/src/main/kotlin/godot/core/Functions.kt
> +        private vararg val parameterTypes: Pair<VariantType, Boolean>
I would rather use it only as a constructor argument to initialize two array of primitives. To avoid an array of complex object in buffer context.

2021-02-27 07:26 UTC, piiertho approved these changes

2021-02-27 09:10 UTC, merged