Add GD print functions
utopia-rise/godot-jvm pull request #87
Opened 2021-03-01 12:16 UTC by chippmann

This resolves #65 and implements GD print functions. It also improves the error output in the garbage collector by printing the actually leaked objects rather than the weak ref's.

An [issue](https://github.com/utopia-rise/godot-jvm/issues/86) was encountered along the way where we leak a `RandomNumberGenerator` when the `GD` object is used. This is not fixed in this PR as it has nothing to do with this addition.

2021-03-01 14:42 UTC, chippmann commented
The tests are now failing because of the issue i created.
Will comment the printing functions for now. Just uncomment them to see that they are working

2021-03-01 22:36 UTC, CedNaru approved these changes

2021-03-02 16:56 UTC, piiertho requested changes

2021-03-02 16:56 UTC, piiertho commented on src/gd_kotlin.h
> +    GDPrintGlue* gd_print_glue;
I would prefer a Bridge in BridgeManager

2021-03-02 16:56 UTC, piiertho commented on src/gd_print_glue.cpp
> +    jni::Env env(p_env);
don't send string through jni, use buffer instead

2021-03-02 16:56 UTC, piiertho commented on src/gd_print_glue.cpp
> +    jni::Env env(p_env);
same.

2021-03-02 16:56 UTC, piiertho commented on src/gd_print_glue.cpp
> +    jni::Env env(p_env);
same.

2021-03-03 16:38 UTC, piiertho approved these changes
Thx !

2021-03-03 17:04 UTC, merged